---
title: "R Notebook"
output: html_notebook
---


```{r}

library(tidyr)
library(devtools)
library(rcfss)
# install_github("uc-cfss/rcfss")

rm(list = ls())
```


```{r}
tidyTable5 <-
  table5 %>%
  #spread(key = century, value = year)
  #gather(key = century, value = year)
  #unite(col = new, century, year, sep = "")
  
tidyTable5
```

```{r}
nextStep <-
  table5 %>%
  #table5 %>% unite(col = new, century, year)
  #table5 %>% unite(col = new, century, year, sep = "")
  #table5 %>% unite(col = year, century, year)

nextStep
```


```{r}

race

race %>%
  spread(key = Time, value = Score, -Name, convert = TRUE) 

```

```{r}

tidyResults <-
  results %>%
  #spread(key = Treatment, value = value)
  #gather(key = Treatment, value = value)
  #unite(key = Treatment, value = value)

```

```{r}
library(stringr)


grades %>%
  gather(key = Quarter, value = Score, Fall:Winter) %>%
  mutate(Test = str_c("Test", Test)) %>%
  ## stop here for exercise
  spread(key = Test, value = Score) %>%
  arrange(ID, Year, Quarter)

```


```{r}

# view
activities

# solution
activities %>%
  gather(key = key, value = value, -id, -trt) %>%
  separate(key, into = c("location", "time")) %>%
  arrange(id, trt, time) %>%
  # stop here for ex
  spread(key = location, value = value)
```


```{r}

library(datasets)

pressure

presidential


cars

```



```{r}


bank <- read.csv("questionbank.csv")
bank = data.frame(lapply(bank, as.character), stringsAsFactors = FALSE)


bank

bank[2,2]

bank[7,2]

```





```{r}

bank <- read.csv("questionbank.csv")
bank = data.frame(lapply(bank, as.character), stringsAsFactors = FALSE)



  value <- reactiveValues(index =  1, mistake = 0, correct = 0)
  ans <- as.matrix(bank[1:9, 6])
  #ans <- data.frame(ans)
  index_list <- reactiveValues(list = 1:9)
  
  observeEvent(input$nextq,{
    value$answerbox <- value$index
    index_list$list = index_list$list[-1]   
    value$index <- index_list$list[1]
    value$answerbox <- value$index
  })

bank[value$index, 2]







```


```{r}


bank <- read.csv("questionbank.csv")
bank = data.frame(lapply(bank, as.character), stringsAsFactors = FALSE)


value <- reactiveValues(index =  1, mistake = 0, correct = 0)
ans <- as.matrix(bank[1:9, 6])
index_list <- reactiveValues(list = 1:9)


value

ans

## rows, columns

bank[1:9, 2]

index_list

seq(from = 1, to = 9, by = 1)

list = seq(from = 1, to = 9, by = 1)

list

```


```{r}

race1 (no code)

race2

race %>%
  spread()







```













